config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#top'
  resources :events, only:[:new, :create, :index, :show, :edit, :update, :destroy] do
  	resource :post_comments, only: [:create, :destroy]
  	resource :participates, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :participates, dependent: :destroy
  attachment :event_image
  validates :event_image, presence: true
  validates :title, presence: true, length: { maximum: 17 }
  validates :date, presence: true
  validates :place, presence: true, length: { maximum: 15 }
  validates :capacity, presence: true
  validates :description, presence: true, length: { maximum: 105 }

  def participated_by?(user)
	participates.where(user_id: user.id).exists?
  end
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :comment, presence: true, length: { maximum: 86 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :participates, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { maximum: 10 }
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
	  @event = Event.new
	end

	def create
	  @event = Event.new(event_params)
	  @event.user_id = current_user.id
	  if @event.save
	  	redirect_to events_path
	  else
	  	render :new
	  end
	end

	def index
	  if Event.ransack(params[:q])
		@search = Event.ransack(params[:q])
		@events = @search.result.page(params[:page]).reverse_order
	  else
		@events = Event.page(params[:page]).reverse_order
	  end
	end

	def show
		@event = Event.find(params[:id])
		#ログインユーザーがイベントに参加している場合
	  if Participate.where(event_id: params[:id]).pluck(:user_id).include?(current_user.id)
		@post_comment = PostComment.new
		#ログインユーザーがイベント主催者の場合
	  elsif Event.where(id: params[:id]).pluck(:user_id).include?(current_user.id)
		@post_comment = PostComment.new
	  else
		redirect_back(fallback_location: events_path)
	  end
	end

	def edit
	  @event = Event.find(params[:id])
	end

	def update
	  @event = Event.find(params[:id])
	  @event.update(event_params)
	  redirect_to events_path
	end

	def destroy
	  event = Event.find(params[:id])
	  event.destroy
	  redirect_to events_path
	end

	private
	  def event_params
	    params.require(:event).permit(:event_image, :title, :date, :place, :capacity, :description)
	  end

end

app/controllers/participates_controller.rb
class ParticipatesController < ApplicationController
	def create
	  @event = Event.find(params[:event_id])
	  @participate = current_user.participates.new(event_id: @event.id)
	  @participates = Participate.where(user_id: @participate.user.id)
	  @events = Event.all
	  @participate.save
	end

	def destroy
	  @event = Event.find(params[:event_id])
	  participate = current_user.participates.find_by(event_id: @event.id)
	  @events = Event.all
	  participate.destroy
	  redirect_to events_path
	end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

	def create
	  event = Event.find(params[:event_id])
	  comment = current_user.post_comments.new(post_comment_params)
	  comment.event_id = event.id
	  comment.save
	  redirect_to event_path(event)
	end

	private

	def post_comment_params
	  params.require(:post_comment).permit(:user_id, :event_id, :comment)
	end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

	skip_before_action :authenticate_user!, only: [:top]

	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@participates = Participate.where(user_id: @user.id).page(params[:page]).reverse_order
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update(user_params)
  	redirect_to user_path(@user.id)
  end

  private

  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_participate.html.erb
<p class="participates_count">
  <span class="participate_users"><%= fa_icon("user") %></span>
  : <%= event.participates.count %>/<%= event.capacity %>名
</p>

<div id ="participate" class="participate_button">
  <%# ログインユーザーがイベント主催者の場合 %>
  <% if event.user.id == current_user.id %>
    <p>
      <%= link_to "トークルームへ", event_path(event), class: "btn talkroom_host"%>
    </p>
  <%# ログインユーザーがイベントに参加している場合 %>
  <% elsif event.participated_by?(current_user) %>
    <p>
      <%= link_to "トークルームへ", event_path(event.id), method: :get, class: "btn talkroom_participate" %>
    </p>
  <%# イベント参加者数が定員に達した場合 %>
  <% elsif event.capacity <= event.participates.count %>
    <p class="capacity_max btn">満員</p>
  <% else %>
    <p>
      <%= link_to "参加", event_participates_path(event), method: :post, remote: true, id:"participate_link_#{event.id}", class: "btn participate" %>
    </p>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
	<p><%= f.attachment_field :event_image %></p>
	<p><%= f.text_field :title, :placeholder => "タイトル" %></p>
	<p><%= f.text_field :date, :placehholder => "日程" %></p>
	<p><%= f.text_field :place, :placeholder => "場所" %></p>
	<p><%= f.number_field :capacity, :placeholder => "定員" %></p>
	<p><%= f.text_area :description , :placeholder => "説明" %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/events/index.html.erb
<div class="event_index">
	<div class="ransack">
		<%= search_form_for @search do |f| %>
			<%= f.search_field :title_cont, :placeholder => "キーワードを入力", class: "search_form" %>
			<%= f.submit '検索',class: 'search_btn'  %>
		<% end %>
	</div>
	<div class="index_border">EVENTS</div>
	<div class="event_boxes clearfix">
		<% @events.each do |event| %>
			<div class="event_box event_box_hover">
				<div class="event_image_wrap">
					<div class="event_image">
						<%= attachment_image_tag event, :event_image,:fill, 325, 210, format:'jpeg' %>
					</div>
				</div>
				<div class="description">
					<div  class = "description-text" >
						<%= event.description %>
					</div>
				</div>
				<p class="event_title">
					<span class="hashtag">
						<%= fa_icon("hashtag") %>
					</span>
					<%= event.title %>
				</p>
				<p class="event_date">
					<span class="calendar">
						<%= fa_icon("calendar") %>
					</span>
					: <%= event.date %>
				</p>
				<p class="event_place">
					<span class="map-marker">
						<%= fa_icon("map-marker") %>
					</span>
					: <%= event.place %>
				</p>
				<div id="participate_btn_<%= event.id %>">
					<%= render partial: 'events/participate', locals: { event: event } %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<p><%= paginate @events, class: "paginate" %></p>
<script>
  $(function() {
    $('.event_box_hover').hover(
      function(){
        $(this).find('.description').fadeIn(150);
        $(this).find('.description-text').fadeIn(500);
        $(this).find('.event_image').css('transform','scale(1.05)').css('transition-duration','0.3s');
        $(this).css('border-bottom','2px solid black');
      },
      function(){
        $(this).find('.description').fadeOut();
        $(this).find('.description-text').fadeOut(500);
        $(this).find('.event_image').css('transform','scale(1.0)');
        $(this).css('border-bottom','1px solid #DDDDDD');
      }
    );
  });
</script>

app/views/events/new.html.erb
<div class="event_new">
	<div class="post_back">
		<div class="post_event">
			<%= form_for (@event) do |f| %>
				<% if @event.errors.any? %>
					<%= @event.errors.count %>のエラーが発生しました
					<%= @event.errors.full_messages.each do |message| %>
						<%= message %>
					<% end%>
				<% end %>
				<p><%= f.attachment_field :event_image, class: "form_new" %></p>
				<p><%= f.text_field :title, :placeholder => "タイトル", class: "form_new" %></p>
				<p><%= f.date_field :date, :placeholder => "日程", class: "form_new" %></p>
				<p><%= f.text_field :place, :placeholder => "場所", class: "form_new" %></p>
				<p><%= f.number_field :capacity, :placeholder => "定員", class: "form_new" %></p>
				<p><%= f.text_area :description, :placeholder => "説明", class: "form_new" %></p>
				<p><%= f.submit '投稿',class: "post_btn" %></p>
			<% end %>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<div class="event_show">
	<div class="show_image">
		<%= attachment_image_tag @event, :event_image, :fill, 1280, 450, format: 'jpeg' %>
	</div>
	<div class="show_discription">
		<p class="show_event_title">
			<%= fa_icon("hashtag") %> <%= @event.title %>
		</p>
	</div>
	<div class="icon left">
		<%= link_to user_path(@event.user) do %>
			<%= attachment_image_tag @event.user, :profile_image, size: "60x60",  fallback: "/images/no_image.jpg" %>
		<% end %>
		<%= @event.user.name %>
		<span class="show_desription_text"><%= @event.description %></span>
	</div>
	<div class="show_items clearfix">
		<p class="show_item"><%= fa_icon("calendar") %> <%= @event.date %></p>
		<p class="show_item"><%= fa_icon("map-marker") %> <%= @event.place %></p>
		<p class="show_item"><%= fa_icon("user") %> <%= @event.participates.count %>/<%= @event.capacity %>名</p>
	</div>
	<div class="show_participate_cancel">
		<%# ログインユーザーがイベントに参加している場合 %>
		<% if @event.participated_by?(current_user) %>
			<%= link_to "参加取消", event_participates_path(@event), method: :delete, class: "participate_cancel" %>
		<% end %>
	</div>
	<div class="host_button">
		<%# ログインユーザーがイベント主催者の場合 %>
		<% if @event.user == current_user %>
			<%= link_to "投稿編集", edit_event_path(@event), class: "event_edit host_btn" %>
			<%= link_to "投稿削除", event_path(@event), method: :delete, class: "event_destroy host_btn" %>
		<% end %>
	</div>
	<div class="show_border"></div>
	<div class="comments left">
		<% @event.post_comments.each do |post_comment| %>
			<p>
				<%= link_to user_path(post_comment.user) do %>
					<%= attachment_image_tag post_comment.user, :profile_image, size: "60x60",  fallback: "no_image.jpeg" %>
				<% end %>
				<%= post_comment.user.name %>
				<span class="show_comment_text"><%= post_comment.comment %></span>
			</p>
		<% end %>
	</div>
	<div class="show_comment_border"></div>
	<div class="comment">
		<%= form_for [@event, @post_comment] do |f| %>
			<span><%= f.text_field :comment, :placeholder => "コメントを入力", class: 'comment_form'  %></span>
			<%= f.submit '送信', class: 'comment_btn' %>
		<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventMatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="logo"><%= link_to "EVENT MATCH",root_path, class: "header_logo" %></div>
      <nav>
        <ul>
          <% if user_signed_in? %>
            <li><%= link_to "イベント一覧", events_path, class: "header_item" %></li>
            <li><%= link_to "イベント募集", new_event_path, class: "header_item" %></li>
            <li><%= link_to "マイページ", user_path(current_user.id), class: "header_item" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_item" %></li>
          <% else %>
            <li><%= link_to "新規会員登録", new_user_registration_path, class: "header_item" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: "header_item" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="footer_title">EVENT MATCH</div>
    </div>
  </body>
</html>

app/views/participates/create.js.erb
$("#participate_btn_<%= @event.id %>").html("<%= j(render partial: 'events/participate', locals: {events: @events, event: @event}) %>");
$("#mypage_participate_btn_<%= @event.id %>").html("<%= j(render partial: 'users/mypage_participate', locals: {participates: @participates, participate: @participate}) %>");

app/views/root/top.html.erb
<div class="top-wrapper">
	<div class="top-container">
		<h1>EVENT MATCH</h1>
		<p>EVENT MATCHはイベントマッチングサイトです。</p>
		<p>参加したいイベントを検索して参加したり、自分でイベントを主催して募集しましょう。</p>
		<div class="btn-wrapper">
			<% if user_signed_in? %>
			<% else %>
				<span class="button signup">
					<%= link_to "新規会員登録", new_user_registration_path, class: "signup_btn" %>
				</span>
				<span class="button signin">
					<%= link_to "ログイン", new_user_session_path, class: "signin_btn" %>
				</span>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_mypage_participate.html.erb
<p class="participates_count">
  <span class="participate_users">
    <%= fa_icon("user") %>
  </span>
  <%# イベントに参加しているユーザーの数 / イベントの定員 %>
	: <%= Participate.where(event_id: participate.event.id ).count %>/<%= participate.event.capacity %>名
</p>
<div class="participate_button">
  <%# ログインユーザーがイベントに参加している場合 %>
  <% if Participate.where(event_id: participate.event_id, user_id: current_user.id) != [] %>
	<p><%= link_to "トークルームへ", event_path(participate.event), class: "btn talkroom_participate" %></p>
  <%# イベント参加者数が定員に達している場合 %>
  <% elsif Participate.where(event_id: participate.event_id).count >= participate.event.capacity %>
	<p class="capacity_max btn">満員</p>
  <% else %>
	<p><%= link_to "参加", event_participates_path(participate.event), method: :post, remote: true, class: "btn participate" %></p>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="user_edit">
	<%= form_for(@user) do |f| %>
		<p><%= f.text_field :name %></p>
		<p><%= f.text_area :introduction %></p>
		<p><%= f.attachment_field :profile_image %></p>
		<p><%= f.submit %></p>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="user_show clearfix">
	<p><%= attachment_image_tag @user, :profile_image, size: "100x100", format: "jpeg", fallback: "/images/no_image.jpg" %></p>
	<p>名前 : <%= @user.name %></p>
	<p>自己紹介 : <%= @user.introduction %></p>
	<p class="profile_edit">
		<% if @user.id == current_user.id %>
			<%= link_to "プロフィール編集", edit_user_path(@user.id),class: "profile_edit_btn" %>
		<% end %>
	</p>
	<div class="user_show_border">PARTICIPATE  PLANS</div>
	<div class="participation_plans">
		<% @participates.each do |participate| %>
			<div class="participate_plan participate_plan_hover">
				<div class="mypage_event_image_wrap">
					<div class="mypage_event_image">
						<%= attachment_image_tag participate.event, :event_image, :fill, 325, 210, format: 'jpeg' %>
					</div>
				</div>
				<div class="mypage_description">
					<div class="mypage_description-text">
						<%= participate.event.description %>
					</div>
				</div>
				<p class="event_title">
					<span class="hashtag">
						<%= fa_icon("hashtag") %>
					</span>
					<%= participate.event.title %>
				</p>
				<p class="event_date">
					<span class="calendar">
						<%= fa_icon("calendar") %>
					</span>
					: <%= participate.event.date %>
				</p>
				<p class="event_place">
					<span class="map-marker">
						<%= fa_icon("map-marker") %>
					</span>
					: <%= participate.event.place %>
				</p>
				<div id="mypage_participate_btn_<%= participate.event.id %>">
					<%= render partial: 'users/mypage_participate', locals: { participate: participate } %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<p><%= paginate @participates, class: "paginate" %></p>
<script>
  $(function() {
    $('.participate_plan_hover').hover(
      function(){
        $(this).find('.mypage_description').fadeIn(150);
        $(this).find('.mypage_description-text').fadeIn(500);
        $(this).find('.mypage_event_image').css('transform','scale(1.05)').css('transition-duration','0.3s');
        $(this).css('border-bottom','2px solid black');
      },
      function(){
        $(this).find('.mypage_description').fadeOut();
        $(this).find('.mypage_description-text').fadeOut(500);
        $(this).find('.mypage_event_image').css('transform','scale(1.0)');
        $(this).css('border-bottom','1px solid #DDDDDD');
      }
    );
  });
</script>